# Generated by Django 2.1.7 on 2019-02-23 11:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('risk_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_values', django.contrib.postgres.fields.jsonb.JSONField()),
                ('risk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_types.RiskType')),
            ],
        ),
    ]
